document.writeln("<link href=\"css/tables.css\" rel=\"stylesheet\" as=\"style\">");
document.writeln("<link rel=\"stylesheet\" href=\"https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css\">");
document.writeln("<table >");
document.writeln("    <tr>");
document.writeln("        <th id=\"downwidth\"></th>");
document.writeln("        <th id=\"tablewidth\">Rank</th>");
document.writeln("        <th>Model</th>");
document.writeln("        <th id=\"tablewidth\">Question Match</th>");
document.writeln("        <th id=\"tablewidth\">Interaction Match</th>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <script type=\"text/javascript\" src=\"js/dropdown.js\"></script>");
document.writeln("        <td><i class=\"fa fa-angle-right\" onclick=\"myFunction(this)\" style=\"cursor:pointer\"></i></td>");
document.writeln("        <td>");
document.writeln("            1");
document.writeln("            <div id=\"dateb\">");
document.writeln("                <p id=\"date\">June 1, 2022</p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>");
document.writeln("            Duorat");
document.writeln("            <div>");
document.writeln("                <p id=\"pretrainedLM\"><i>bert-base-multilingual-uncased</i></p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>0.493</td>");
document.writeln("        <td>0.178</td> ");
document.writeln("    </tr>");
document.writeln("    <tr style=\"display:none\" id=\"tr1\" >");
document.writeln("        <td></td>");
document.writeln("        <td colspan=\"4\">");
document.writeln("          <p  align=\"left\"><b>Model:</b> Base</p>");
document.writeln("          <p  align=\"left\"><b>Affliation:</b> Xi'an Jiaotong University</p>");
document.writeln("          <p  align=\"left\"><b>Dev Question Match:</b> 0.2209</p>");
document.writeln("          <p  align=\"left\"><b>Dev Interaction Match:</b> 0.0570</p>");
document.writeln("          <p  align=\"left\"><b>Paper:</b> Not yet publicly available</p>");
document.writeln("          <p  align=\"left\"><b>Code:</b> <a href=\"https://github.com/xjtu-intsoft/mChase/tree/page\">https://github.com/xjtu-intsoft/mChase/tree/page</a></p>");
document.writeln("        </td>");
document.writeln("");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("");