document.writeln("<link href=\"css/tables.css\" rel=\"stylesheet\" as=\"style\">");
document.writeln("<link rel=\"stylesheet\" href=\"https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css\">");
document.writeln("<table >");
document.writeln("    <tr>");
document.writeln("        <th id=\"downwidth\"></th>");
document.writeln("        <th id=\"tablewidth\">Rank</th>");
document.writeln("        <th>Model</th>");
document.writeln("        <th id=\"tablewidth\">Question Match</th>");
document.writeln("        <th id=\"tablewidth\">Interaction Match</th>");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <script type=\"text/javascript\" src=\"js/dropdown.js\"></script>");
document.writeln("        <td><i class=\"fa fa-angle-right\" onclick=\"myFunction(this)\" style=\"cursor:pointer\"></i></td>");
document.writeln("        <td>");
document.writeln("            1");
document.writeln("            <div id=\"dateb\">");
document.writeln("                <p id=\"date\">June 1, 2022</p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>");
document.writeln("            Duorat");
document.writeln("            <div>");
document.writeln("                <p id=\"pretrainedLM\"><i>Bert-base-Chinese</i></p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>0.493</td>");
document.writeln("        <td>0.178</td> ");
document.writeln("    </tr>");
document.writeln("    <tr style=\"display:none\" id=\"tr1\" >");
document.writeln("        <td></td>");
document.writeln("        <td colspan=\"4\">");
document.writeln("          <p  align=\"left\"><b>Model:</b> Duorat</p>");
document.writeln("          <p  align=\"left\"><b>Affliation:</b> Element AI</p>");
document.writeln("          <p  align=\"left\"><b>Dev Question Match:</b> 0.493</p>");
document.writeln("          <p  align=\"left\"><b>Dev Interaction Match:</b> 0.178</p>");
document.writeln("          <p  align=\"left\"><b>Paper: <a href=\"https://arxiv.org/abs/2010.11119.pdf\">DuoRAT: Towards Simpler Text-to-SQL Models</a></b> </p>");
document.writeln("          <p  align=\"left\"><b>Code: <a href=\"https://github.com/ServiceNow/duorat\">https://github.com/ServiceNow/duorat</a></b> </p>");
document.writeln("        </td>");
document.writeln("");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <script type=\"text/javascript\" src=\"js/dropdown.js\"></script>");
document.writeln("        <td ><i class=\"fa fa-angle-right\" onclick=\"myFunction(this)\" style=\"cursor:pointer\"></i></td>");
document.writeln("        <td>");
document.writeln("            2");
document.writeln("            <div id=\"dateb\">");
document.writeln("                <p id=\"date\">June 1, 2021</p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>");
document.writeln("            IGSQL");
document.writeln("            <div>");
document.writeln("                <p id=\"pretrainedLM\"><i>Bert-base-Chinese</i></p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>0.404</td>");
document.writeln("        <td>0.147</td>");
document.writeln("    </tr>");
document.writeln("    <tr class=\"dropdown\" style=\"display:none\" id=\"tr2\">");
document.writeln("        <td></td>");
document.writeln("        <td colspan=\"4\">");
document.writeln("          <p  align=\"left\"><b>Model:</b> IGSQL</p>");
document.writeln("          <p  align=\"left\"><b>Affliation:</b> Peking University</p>");
document.writeln("          <p  align=\"left\"><b>Dev Question Match:</b> 0.414</p>");
document.writeln("          <p  align=\"left\"><b>Dev Interaction Match:</b> 0.200</p>");
document.writeln("          <p  align=\"left\"><b>Paper:</b> <a href=\"https://aclanthology.org/2020.emnlp-main.560.pdf\">IGSQL</a></p>");
document.writeln("          <p  align=\"left\"><b>Code: <a href=\"https://github.com/headacheboy/IGSQL\">https://github.com/headacheboy/IGSQL</a></b> </p>");
document.writeln("        </td>");
document.writeln("");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <script type=\"text/javascript\" src=\"js/dropdown.js\"></script>");
document.writeln("        <td><i class=\"fa fa-angle-right\" onclick=\"myFunction(this)\" style=\"cursor:pointer\"></i></td>");
document.writeln("        <td>");
document.writeln("            3");
document.writeln("            <div id=\"dateb\">");
document.writeln("                <p id=\"date\">June 1, 2021</p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>");
document.writeln("            EditedSQL");
document.writeln("            <div>");
document.writeln("                <p id=\"pretrainedLM\"><i>Bert-base-Chinese</i></p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>0.378</td>");
document.writeln("        <td>0.147</td>");
document.writeln("    </tr>");
document.writeln("    <tr class=\"dropdown\" style=\"display:none\" id=\"tr3\">");
document.writeln("        <td></td>");
document.writeln("        <td colspan=\"4\">");
document.writeln("          <p  align=\"left\"><b>Model:</b> EditedSQL</p>");
document.writeln("          <p  align=\"left\"><b>Affliation:</b> Yale University, Salesforce Research, and Corenell University</p>");
document.writeln("          <p  align=\"left\"><b>Dev Question Match:</b> 0.377</p>");
document.writeln("          <p  align=\"left\"><b>Dev Interaction Match:</b> 0.174</p>");
document.writeln("          <p  align=\"left\"><b>Paper:</b> <a href=\"https://arxiv.org/pdf/1909.00786.pdf\">EditedSQL</a></p>");
document.writeln("          <p  align=\"left\"><b>Code:</b> <a href=\"https://github.com/ryanzhumich/sparc_atis_pytorch\">https://github.com/ryanzhumich/sparc_atis_pytorch</a></p>");
document.writeln("        </td>");
document.writeln("");
document.writeln("    </tr>");
document.writeln("    <tr>");
document.writeln("        <script type=\"text/javascript\" src=\"js/dropdown.js\"></script>");
document.writeln("        <td><i class=\"fa fa-angle-right\" onclick=\"myFunction(this)\" style=\"cursor:pointer\"></i></td>");
document.writeln("        <td>");
document.writeln("            4");
document.writeln("            <div id=\"dateb\">");
document.writeln("                <p id=\"date\">June 1, 2021</p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>");
document.writeln("            RatSQL+Concat");
document.writeln("            <div>");
document.writeln("                <p id=\"pretrainedLM\"><i>Bert-base-Chinese</i></p>");
document.writeln("            </div>");
document.writeln("        </td>");
document.writeln("        <td>0.325</td>");
document.writeln("        <td>0.098</td>");
document.writeln("    </tr>");
document.writeln("    <tr class=\"dropdown\" style=\"display:none\" id=\"tr4\">");
document.writeln("        <td></td>");
document.writeln("        <td colspan=\"4\">");
document.writeln("          <p  align=\"left\"><b>Model:</b> RatSQL + Concat</p>");
document.writeln("          <p  align=\"left\"><b>Affliation:</b> University of Edinburgh, UC Berkeley, and Microsoft Research</p>");
document.writeln("          <p  align=\"left\"><b>Dev Question Match:</b> 0.351</p>");
document.writeln("          <p  align=\"left\"><b>Dev Interaction Match:</b> 0.146</p>");
document.writeln("          <p  align=\"left\"><b>Paper: <a href=\"https://arxiv.org/pdf/1911.04942.pdf\">RatSQL</a></b> </p>");
document.writeln("          <p  align=\"left\"><b>Code: <a href=\"https://github.com/Microsoft/rat-sql\">https://github.com/Microsoft/rat-sql</a></b> </p>");
document.writeln("        </td>");
document.writeln("");
document.writeln("    </tr>");
document.writeln("</table>");
document.writeln("");